# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_de_naissance', models.DateField()),
                ('courriel', models.EmailField(max_length=254)),
                ('tel_fixe', models.CharField(max_length=20)),
                ('tel_mobile', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=32)),
            ],
        ),
    ]
