# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscoop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='courriel',
            new_name='couriel',
        ),
    ]
